require "nathan.options"
require "nathan.keymaps"
require "nathan.plugins"
require "nathan.colourscheme"
require "nathan.cmp"
require "nathan.lsp"
require "nathan.telescope"
require "nathan.whichkey"
